// default package
// Generated 2017-5-4 21:20:27 by Hibernate Tools 3.4.0.CR1

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private int classCode;
	private String classRoom;
	private String classSection;
	private String classStartDate;
	private String classTime;
	private Integer crsCode;

	public Class() {
	}

	public Class(int classCode) {
		this.classCode = classCode;
	}

	public Class(int classCode, String classRoom, String classSection, String classStartDate, String classTime,
			Integer crsCode) {
		this.classCode = classCode;
		this.classRoom = classRoom;
		this.classSection = classSection;
		this.classStartDate = classStartDate;
		this.classTime = classTime;
		this.crsCode = crsCode;
	}

	public int getClassCode() {
		return this.classCode;
	}

	public void setClassCode(int classCode) {
		this.classCode = classCode;
	}

	public String getClassRoom() {
		return this.classRoom;
	}

	public void setClassRoom(String classRoom) {
		this.classRoom = classRoom;
	}

	public String getClassSection() {
		return this.classSection;
	}

	public void setClassSection(String classSection) {
		this.classSection = classSection;
	}

	public String getClassStartDate() {
		return this.classStartDate;
	}

	public void setClassStartDate(String classStartDate) {
		this.classStartDate = classStartDate;
	}

	public String getClassTime() {
		return this.classTime;
	}

	public void setClassTime(String classTime) {
		this.classTime = classTime;
	}

	public Integer getCrsCode() {
		return this.crsCode;
	}

	public void setCrsCode(Integer crsCode) {
		this.crsCode = crsCode;
	}

}
