// default package
// Generated 2017-5-4 21:20:27 by Hibernate Tools 3.4.0.CR1

/**
 * Enrolment generated by hbm2java
 */
public class Enrolment implements java.io.Serializable {

	private int classCode;
	private String enComments;
	private String enGrade;
	private Integer stuId;

	public Enrolment() {
	}

	public Enrolment(int classCode) {
		this.classCode = classCode;
	}

	public Enrolment(int classCode, String enComments, String enGrade, Integer stuId) {
		this.classCode = classCode;
		this.enComments = enComments;
		this.enGrade = enGrade;
		this.stuId = stuId;
	}

	public int getClassCode() {
		return this.classCode;
	}

	public void setClassCode(int classCode) {
		this.classCode = classCode;
	}

	public String getEnComments() {
		return this.enComments;
	}

	public void setEnComments(String enComments) {
		this.enComments = enComments;
	}

	public String getEnGrade() {
		return this.enGrade;
	}

	public void setEnGrade(String enGrade) {
		this.enGrade = enGrade;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

}
