// default package
// Generated 2017-5-4 21:20:27 by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int stuId;
	private String stuAdd;
	private Integer stuAge;
	private String stuEmail;
	private String stuFname;
	private String stuLname;
	private Integer stuPhone;

	public Student() {
	}

	public Student(int stuId) {
		this.stuId = stuId;
	}

	public Student(int stuId, String stuAdd, Integer stuAge, String stuEmail, String stuFname, String stuLname,
			Integer stuPhone) {
		this.stuId = stuId;
		this.stuAdd = stuAdd;
		this.stuAge = stuAge;
		this.stuEmail = stuEmail;
		this.stuFname = stuFname;
		this.stuLname = stuLname;
		this.stuPhone = stuPhone;
	}

	public int getStuId() {
		return this.stuId;
	}

	public void setStuId(int stuId) {
		this.stuId = stuId;
	}

	public String getStuAdd() {
		return this.stuAdd;
	}

	public void setStuAdd(String stuAdd) {
		this.stuAdd = stuAdd;
	}

	public Integer getStuAge() {
		return this.stuAge;
	}

	public void setStuAge(Integer stuAge) {
		this.stuAge = stuAge;
	}

	public String getStuEmail() {
		return this.stuEmail;
	}

	public void setStuEmail(String stuEmail) {
		this.stuEmail = stuEmail;
	}

	public String getStuFname() {
		return this.stuFname;
	}

	public void setStuFname(String stuFname) {
		this.stuFname = stuFname;
	}

	public String getStuLname() {
		return this.stuLname;
	}

	public void setStuLname(String stuLname) {
		this.stuLname = stuLname;
	}

	public Integer getStuPhone() {
		return this.stuPhone;
	}

	public void setStuPhone(Integer stuPhone) {
		this.stuPhone = stuPhone;
	}

}
